export const metadata = {
  title: '',
  description: 'Generated by create next app',
}

export const menu_data = [
	{
		link: "/",
		title: "Home",
	},
	{
		link: "/projects",
		title: "Projects",
	},
	{
		link: "/contact",
		title: "Contact",
	}
]

export const about_me = {
	Name: "Pedro Mota",
	Skills: ["Team Work", ],
	Apresentation: "I'm a Software Developer, Currently Studing at 42 School ..."
}